### ISSUE TITLE
Stylus

### ISSUE THREAD

**Issue by hinell** [kitze/extension-twitter-no-views#1]
[Stylus](https://github.com/openstyles/stylus) can also be used to hide views. It doesn't work perfectly though.

```css
      div[aria-label*="replies"]  > div:first-child
    , div[aria-label*="reply"]    > div:first-child
    , div[aria-label*="likes"]    > div:first-child
    , div[aria-label*="like"]     > div:first-child
    , div[aria-label*="retweets"] > div:first-child
    , div[aria-label*="retweet"]  > div:first-child
    {
        display: none;
    }
```
